# Generated by Django 6.0.4 on 2026-04-14 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('suburb', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('garages', models.FloatField(blank=True, null=True)),
                ('erf_size', models.CharField(blank=True, max_length=100)),
                ('floor_size', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('agent_name', models.CharField(blank=True, max_length=200)),
                ('agency', models.CharField(blank=True, max_length=200)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('file', models.FileField(upload_to='listings/%Y/%m/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.listing')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('listing', 'source_url')},
            },
        ),
    ]
