# Generated by Django 6.0.4 on 2026-04-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_headline_listing_latitude_listing_levies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='main.listinggroup'),
        ),
    ]
