# Generated by Django 6.0.4 on 2026-04-15 18:08

from django.db import migrations, models


def backfill_sizes(apps, schema_editor):
    from main.models import parse_size_m2
    Listing = apps.get_model('main', 'Listing')
    updates = []
    for l in Listing.objects.all().only('id', 'erf_size', 'floor_size'):
        l.erf_size_m2 = parse_size_m2(l.erf_size)
        l.floor_size_m2 = parse_size_m2(l.floor_size)
        updates.append(l)
    Listing.objects.bulk_update(updates, ['erf_size_m2', 'floor_size_m2'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listinggroup_listing_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='erf_size_m2',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_size_m2',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_sizes, migrations.RunPython.noop),
    ]
