# Generated by Django 6.0.4 on 2026-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_listing_address_null_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-listed_at']},
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_hash',
            field=models.CharField(blank=True, default='', db_index=True, max_length=32),
        ),
    ]
