# Generated by Django 6.0.4 on 2026-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='phash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
