# Generated by Django 6.0.4 on 2026-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_phash_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
