# Generated by Django 6.0.4 on 2026-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_listing_notes_listinggroup_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rechecked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
